spring.application.name=rest-service
spring.datasource.url=jdbc:mysql://localhost:3306/db_calidad?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Calidad2026
# Crea las tablas si no existen y las actualiza si cambias algo en tus clases Java
spring.jpa.hibernate.ddl-auto=update

# El dialecto de SQL a utilizar
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Para ver en la consola de VSC las sentencias SQL que hace Spring por debajo
spring.jpa.show-sql=true