package com.example.restservice;
import jakarta.persistence.*;

@Entity
public enum Categoria {
    AMIGOS,
    APRENDIZAJE,
    BANCO,
    CAMINATA,
    CARRERA,
    CICLISMO,
    CINE,
    COCINAR,
    COMPRA,
    CURSO,
    DENTISTA,
    DEPORTE,
    DESCANSO,
    ENTRENAMIENTO,
    ESTUDIO,
    EVENTO,
    FACTURAS,
    FAMILIA,
    FINANZAS,
    FIESTA,
    GIMNASIO,
    HOGAR,
    INVESTIGACION,
    LIMPIEZA,
    LECTURA,
    MEDICO,
    MANTENIMIENTO,
    MUSICA,
    OCIO,
    PAGOS,
    PROYECTO,
    REUNION,
    SALUD,
    SERIES,
    SOCIAL,
    TAREA_ADMINISTRATIVA,
    TERAPIA,
    TRABAJO,
    VACACIONES,
    VIAJE,
    VIDEOJUEGOS,
    YOGA,
    OTRO
}


