name: Maven Site & Peformance & Integration Tests

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 18-23/2 * * *'  # 20:00–01:00 CET
    - cron: '0 0-6/2 * * *'    # 02:00–08:00 CET
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Calidad2026
          MYSQL_DATABASE: db_calidad
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -pCalidad2026"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL..."
          until mysqladmin ping -h 127.0.0.1 -uroot -pCalidad2026 --silent; do
            sleep 2
          done
        
      - name: Run DB initialization script
        working-directory: rest-service
        run: |
          echo "Running DB setup..."
          mysql -h 127.0.0.1 -uroot -pCalidad2026 < src/main/resources/db_calidad.sql

      - name: Run Unit tests and generate converage report
        working-directory: rest-service
        run: mvn test jacoco:report
      
      - name: Run Integration Tests
        working-directory: rest-service
        run: mvn -Pintegration integration-test

      - name: Run Performance Tests
        working-directory: rest-service
        run: mvn -Pperformance integration-test

      - name: Generate Maven Site
        working-directory: rest-service
        run: mvn site

      - name: Ensure that the performance reports are also moved into the target\site\reports folder
        working-directory: rest-service
        run: mvn -Pperformance resources:copy-resources@copy-perf-report
